### ISSUE TITLE
LCAM: Test Results 

### ISSUE THREAD

**Issue by LoicNyssen** [NES-NN/team-management#11]
Evidence of Testing. Specifically:
    User Acceptance Tests to verify and validate support for the CCRD use case, together with test results.
    Unit and Integration Tests to verify implementation of the CCRD use case.

Tests conform with the objectives of master test plan and all test quality criteria (well organised, well named, well explained, and well targeted , supported by clear evaluation criteria and specific test data).

A suite of user acceptance tests for the CCRD use case covering normal and all alternate and exception flows has been specified, and scripts exist to support those tests.

A clear and comprehensive report detailing the results of carrying out those UATs is available.

A set of unit and integration tests that exactly conforms with the master test plan objectives is integrated into the development environment.

Evidence for all unit and integration test results is available.

**Comment by ACoderLife** [comment]
Jim wanted pictures, if possible of the results

**Comment by LoicNyssen** [comment]
https://github.com/NES-NN/team-management/commit/d8b9b4ce7f3efc1699951fd9ce54eef31b2baf8b
