### ISSUE TITLE
LCAM: Revised Project Plan 

### ISSUE THREAD

**Issue by LoicNyssen** [NES-NN/team-management#12]
A Revised Project Plan which sets out the final schedule for implementing all remaining functionality for the project.

The revised project plan specifes a detailed, specific, realistic and achievable schedule to implement the remaining functional and non-functional requirements of the project, and to complete user acceptance testing and deployment.

The plan is clearly related to the risk prioritisation principles of the UP, and the specific risks of the project.

The plan specifies clear and concrete functional targets (ie use cases to be implemented) with intended outcomes for each iteration of the Construction Phase, along with outcomes for other necessary activities.

The plan makes clear and specific allowances for contingencies.

**Comment by ACoderLife** [comment]
This is our plan for running the experiments.
Should include next term.

**Comment by LoicNyssen** [comment]
https://github.com/NES-NN/team-management/commit/d8b9b4ce7f3efc1699951fd9ce54eef31b2baf8b
