### ISSUE TITLE
LCAM: Revised Vision

### ISSUE THREAD

**Issue by LoicNyssen** [NES-NN/team-management#5]
A Revised Project Vision, which sets out the final concept for the completed application.

All HD criteria as specified in LCOM Vision criteria.

The Vision has been thoroughly updated to reflect any and all changes in project scope.

The Vision is completely consistent with the revised requirement model.

There is a change log that records and explains specific changes that have been made.

The Vision reflects all lessons learned and the outcomes of any risk mitigation strategies that have been enacted.

**Comment by ACoderLife** [comment]
Focus on the research question and why it is interesting?
Add references to the current state of the field

**Comment by LoicNyssen** [comment]
https://github.com/NES-NN/team-management/commit/d8b9b4ce7f3efc1699951fd9ce54eef31b2baf8b
