### ISSUE TITLE
LCAM: Revised Requirement Model 

### ISSUE THREAD

**Issue by LoicNyssen** [NES-NN/team-management#6]
A Revised Requirement Model which sets out the final functional and non-functional requirements, the data model, and includes a Full Use Case Description for the CCRD use case.

All HD criteria as specified in LCOM Requirement Model criteria.

The requirement model includes a  full use case description for the CCRD use case which identifies the normal and all alternate and exception flows,  adheres to sound use case description conventions, and also identifies non-functional requirements for the use case.

The requirement model sets out a comprehensive set of realistic and achieveable of specific functional and non-functional goals for the project.

The requirement model reflects all lessons learned during the Elaboration Phase.

**Comment by ACoderLife** [comment]
Focus on the requirements that this research project will need in order to run the experiments.

**Comment by LoicNyssen** [comment]
https://github.com/NES-NN/team-management/commit/d8b9b4ce7f3efc1699951fd9ce54eef31b2baf8b
