### ISSUE TITLE
LCAM: Final Architecture

### ISSUE THREAD

**Issue by LoicNyssen** [NES-NN/team-management#7]
A Final Architecture which explains and illustrates the final approach and technological platform that will be used to support the completed implementation.

All HD criteria as specified in LCOM Proposed Architecture criteria.

The architecture clearly explains the approach used to implement the CCRD use case, and supports all remaining functionality and system qualities to be implemented.

The architecture reflects all lessons learned during the Elaboration Phase.

**Comment by ACoderLife** [comment]
Describe the testbed "gym" docker container, etc.

**Comment by LoicNyssen** [comment]
Any ideas on what diagrams we will need?

**Comment by LoicNyssen** [comment]
https://github.com/NES-NN/team-management/commit/d8b9b4ce7f3efc1699951fd9ce54eef31b2baf8b
