### ISSUE TITLE
LCAM: Revised Risk List 

### ISSUE THREAD

**Issue by LoicNyssen** [NES-NN/team-management#8]
A Revised Risk List which details the status of all risks and mitigation strategies.

All HD criteria as specified in LCOM Risk List criteria.

Any and all risks and issues that became apparent during the Elaboration Phase, and their associated mitigation strategies have been added to the risk list at the time they became apparent, as evidenced through version control.

The risk list has been updated to show the current status of all risks and mitigations strategies.

**Comment by ACoderLife** [comment]
Add risks related to research.  For example, tests run didn't result in conclusive values. etc.

**Comment by jbeemster** [comment]
Need to do this soon so that we can address top level risks for LCAM.

**Comment by LoicNyssen** [comment]
https://github.com/NES-NN/team-management/commit/d8b9b4ce7f3efc1699951fd9ce54eef31b2baf8b
