### ISSUE TITLE
LCAM: Revised Master Test Plan 

### ISSUE THREAD

**Issue by LoicNyssen** [NES-NN/team-management#9]
A Revised Master Test Plan - which sets out the final concept of the test regime.

All HD criteria as specified in LCOM Master Test Plan criteria.

The master test plan has been revised, refined, and expanded in the light of experience gained during the Elaboration phase.

The master test plan sets out a very high quality, well thought out, clearly prioritised, well justified, reasonable and achievable plan for testing during the remaining development.

**Comment by ACoderLife** [comment]
Test that the testbed actually works.
Test that the strategies return the correct results

**Comment by LoicNyssen** [comment]
https://github.com/NES-NN/team-management/commit/d8b9b4ce7f3efc1699951fd9ce54eef31b2baf8b
